---
title: 异常处理
summary: Java的常见异常和处理方法以及自定义异常类
tags:
  - Java
  - 异常
categories:
  - Java
abbrlink: 28877bf
date: 2021-12-14 19:21:37
---

# 一、异常处理

## 1.1 异常概述与异常体系结构

在使用计算机语言进行项目开发的过程中，即使程序员把代码写得尽善尽美，在系统的运行过程中仍然会遇到一些问题，因为很多问题不是靠代码能够避免的，比如： 客户输入数据的格式、读取文件是否存在、网络是否始终保持通畅等等 

- 异常 ：在Java语言中将程序执行中发生的不正常情况称为异常 。（开发过程中的语法错误和逻辑错误不是异常）
- Java 程序在执行过程中所发生的异常事件可分为两类：
    - Error：Java 虚拟机无法解决的严重问题 。如： JVM系统内部错误 、资源耗尽等严重情况。比如：StackOverflowError和OutOfMemoryError。 一般不编写针对性的代码进行处理
    - Exception：其它因编程错误或偶然的外在因素导致的一般性问题可以使用针对性的代码进行处理 。 例如：空指针访问、试图读取不存在的文件、网络连接中断、数组下标越界

- 对于这些错误 一般有两种解决方法：一是遇到错误就终止程序的运行。另一种方法是由程序员在编写程序时就考虑到错误的检测 、 错误消息的提示 以及错误的处理。
- 捕获错误最理想的是在编译期间， 但有的错误只有在运行时才会发生 。比如：除数为0、数组下标越界等
    - 分类： 编译时异常和运行时异常

![异常结构体系](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-1884970a.jpeg)

1. 运行时异常：
    - 是指编译器不要求强制处置的异常。一般是指编程时的逻辑错误，是程序员应该积极避免其出现的异常。 java.lang.RuntimeException类及它的子类都是运行时异常
    - 对于这类异常，可以不作处理，因为这类异常很普遍，若全处理可能会对程序的可读性和运行效率产生影响
2. 编译时异常：
    - 是指编译器要求必须处置的异常。即程序在运行时由于外界因素造成的一般性异常。 编译器要求Java程序必须捕获或声明所有编译时异常
    
    - 对于这类异常，如果程序不处理，可能会带来意想不到的结果
    
        

## 1.2 常见异常

- java.lang.RuntimeException
    - NullPointerException
    - ArrayIndexOutOfBoundsException
    - ClassCastException
    - NumberFormatException
    - InputMismatchException
    - ArithmeticException
    - ……
    
- java.io.IOExeption
    - FileNotFoundException
    - EOFException
    
- java.lang.ClassNotFoundException

- java.lang.InterruptedException

- java.io.FileNotFoundException

- java.sql.SQLException

    

### 1.2.1 常见异常之ArrayIndexOutOfBoundsException（数组下标越界异常）

```java
public class IndexOutExp {
    public static void main(String[] args) {
        String[] friends = {"lisa", "bily", "kessy"};
        for (int i = 0; i < 5; i++) {
            System.out.println(friends[i]); //不存在friends[4]
        }
        System.out.println("\nthis is the end");
    }
}
```

程序IndexOutExp.java编译正确，运行结果： 

![image-20210831221121552](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-5c5f9661.png)



### 1.2.2 常见异常之NullPointerException（空指针异常）

```java
public class NullRef {
    int i = 1;
    
    public static void main(String[] args) {
        NullRef t = new NullRef();
        t = null;
        System.out.println(t);
    }
}
```

程序NullRef.java编译正确，运行结果： 

![image-20210911222154772](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-8e174c73.png)



### 1.2.3 常见异常之ArithmeticException（算术运算异常）

```java
public class DivideZero {
    int x;
    
    public static void main(String[] args) {
        int y;
        DivideZero c = new DivideZero();
        y = 3 / c.x;	//除数为0
        System.out.println("program ends OK!");
    }
}
```

程序ArithmeticException.java编译正确，运行结果： 

![image-20210911222803042](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-1fd55af3.png)



### 1.2.4 常见异常之ClassCastException（类型匹配异常）

```java
public class Order {
    public static void main(String[] args) {
        Object obj = new Date();
        Order order;
        order = (Order) obj;
        System.out.println(order);
    }
}
```

程序Order.java编译正确，运行结果：

![image-20210911223112897](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-f0a82b55.png)



## 1.3 异常处理机制一：try-catch-finally

- Java 提供的是异常处理的抓抛模型
- Java 程序的执行过程中如出现异常，会生成一个异常类对象，该异常对象将被提交给 Java 运行时系统，这个过程称为抛出异常
- 异常对象的生成
    - 由虚拟机自动生成：程序运行过程中，虚拟机检测到程序发生了问题，如果在当前代码中没有找到相应的处理程序，就会在后台自动创建一个对应异常类的实例对象并抛出，自动抛出
    - 由开发人员手动创建：`Exception exception = new ClassCastException();`创建好的异常对象不抛出对程序没有任何影响，和创建一个普通对象 一样

![image-20210911223559802](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-4c93fe13.png)

- 如果一个方法内抛出异常，该异常对象会被抛给调用者方法中处理。如果异常没有在调用者方法中处理，它继续被抛给这个调用方法的上层方法 。这个过程将一直继续下去，直到异常被处理 。这一过程称为捕获异常
- 如果一个异常回到 main() 方法并且 main() 也不处理则程序运行终止
- 程序员通常只能处理 Exception，而对 Error 无能为力

异常处理是通过 `try-catch-finally` 语句实现的:

```java
try {
    可能产生异常的代码
} catch (ExceptionName1 e) {
    当产生ExceptionName1型异常时的处置措施
} catch (ExceptionName e) {
    当产生ExceptionName1型异常时的处置措施
} [finally {
    无论是否发生异常都要执行的语句
}]
```

- try
    - 捕获异常的第一步是用`try{ }`语句块选定捕获异常的范围，将可能出现异常的代码放在 try 语句块中 
- catch (Exceptiontype e)
    - 在 catch 语句块中是对异常对象进行处理的代码。每个 try 语句块可以伴随一个或多个 catch语句用于处理可能产生的不同类型的异常对象 
    - 捕获异常的有关信息：与其它对象一样，可以访问一个异常对象的成员变量或调用它的方法
        - getMessage()：获取异常信息，返回字符串
        - printStackTrace()：获取异常类名和异常信息，以及异常出现在程序中的位置。返回值 为void

![image-20210911224632235](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-b091fb0c.png)

- finally
    - 捕获异常的最后一步是通过 finally 语句为异常处理提供一个统一的出口，使得在控制流转到程序的其它部分以前，能够对程序的状态作统一的管理
    - 不论在 try 代码块中是否发生了异常事件，catch 语句是否执行，catch 语句是否有异常， catch 语句中是否有 return，finally 块中的语句都会被执行
    - finally 语句和 catch 语句是任选的

![image-20210911224827938](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-72d467a2.png)

### 1.3.1 举例

例一：

```java
public class IndexOutExp {
    public static void main(String[] args) {
        String friends[] = {"lisa", "bily", "kessy"};
        try {
            for (int i = 0; i < 5; i++) {
                System.out.println(friends[i]);
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("index err");
        }
        System.out.println("\nthis is the end");
    }
}
```

运行结果如下：

![image-20210911225831080](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-6ff78c50.png)



例二：

```java
public class DivideZero {
    int x;
    public static void main(String[] args) {
        int y;
        DivideZero c = new DivideZero();
        try {
            y = 3 / c.x;
        } catch (ArithmeticException e) {
            System.out.println("divide by zero error!");
        }
        System.out.println("program ends OK!");
    }
}
```

运行结果如下：

![image-20210912100539423](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-10ebc5b3.png)



### 1.3.2 不捕获异常时的情况

- 前面使用的异常都是 RuntimeException 类或是它的子类，这些类的异常的特点是：即使没有使用 try 和 catch 捕获，Java 自己也能捕获，并且编译通过，但运行时会发生异常使得程序运行终止 
- 如果抛出的异常是 IOException 等类型的非运行时异常，则 必须捕获，否则编译错误 。也就是说，我们必须处理编译时异常，将异常进行捕捉，转化为运行时异常

#### IOException异常处理举例

```java
import java.io.File;
import java.io.FileInputStream;

public class IOExp {
    public static void main(String[] args) {
        FileInputStream in = new FileInputStream("test.txt");
        int b;
        b = in.read();
        while (b != -1) {
            System.out.print((char)b);
            b = in.read();
        }
        in.close();
    }
}
```

```java
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

public class IOExp {
    public static void main(String[] args) {
        try {
            FileInputStream in = new FileInputStream("test.txt");
            int b;
            b = in.read();
            while (b != -1) {
                System.out.print((char) b);
                b = in.read();
            }
            in.close();
        } catch (IOException e) {
            System.out.println(e);
        } finally {
            System.out.println(" It`s Ok!");
        }
    }
}
```



## 1.4 异常处理机制二：throw

- 申明抛出异常是 Java 中处理异常的第二种方式
    - 如果一个方法中的语句执行时可能生成某种异常，但是并不能确定如何处理这种异常，则此方法应显示地声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的 调用者 负责处理 
    - 在方法声明中用 throws 语句可以声明抛出异常的列表，throws 后面的异常类型可以是方法中产生的异常类型也可以是它的父类



例：

```java
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

public class ThrowsTest {
    public static void main(String[] args) {
        
    }
    
    public void readFile() throws IOException {
        File file;
        FileInputStream in = new FileInputStream("test.txt");
        int b;
        b = in.read();
        while (b != 1) {
            System.out.println((char)b );
            b = in.read();
        }
        in.close();
    }
}
```

![image-20210912102025470](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-e2fe7ea2.png)

### 1.4.1 重写方法声明抛出异常的原则

- 重写方法不能抛出比被重写方法范围更大的异常类型。 在多态的情况下对 methodA 方法的调用 异常的捕获按父类声明的异常处理

![image-20210912102219614](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-a91e3ee6.png)



## 1.5 手动抛出异常

- Java 异常类对象除在程序执行过程中出现异常时由系统自动生成并抛出，也可根据需要使用人工创建并抛出 
    - 首先要生成异常类对象，然后通过 throw 语句实现抛出操作
    - 可以抛出的异常必须是 Throwable 或其子类的实例。下面的语句在编译时将会产生语法错误



## 1.6 用户自定义异常类

- 一般地，用户自定义异常类都是 RuntimeException的 子类
- 自定义异常类通常需要编写几个重载的构造器
- 自定义异常需要提供 serialVersionUID
- 自定义的异常通过 throw 抛出
- 自定义异常最重要的是异常类的名字，当异常出现时，可以根据名字判断异常类型



用户自定义异常类MyException，用于描述数据取值范围错误信息。用户自己的异常类必须继承现有的异常类

```java
public class MyException extends Exception {
    static final long serialVersionUID = -3387516993124229948L;
    private int idnumber;

    public MyException(String message, int idnumber) {
        super(message);
        this.idnumber = idnumber;
    }

    public int getId() {
        return idnumber;
    }
}
```

```java
class MyExpTest {
    public void regist(int num) throws MyException {
        if (num < 0) {
            throw new MyException("人数为负值，不合理", 3);
        } else {
            System.out.println("登记人数" + num);
        }
    }
    
    public void manager() {
        try {
            regist(100);
        } catch (MyException e) {
            System.out.println("登记失败，出错种类" + e.getId());
        }
        System.out.println("本次登记操作结束");
    }

    public static void main(String[] args) {
        MyExpTest t = new MyExpTest();
        t.manager();
    }
}
```





## 1.6 总结

![image-20210912103337652](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-45f393e1.png)



### 1.6.1 异常

#### 1. 异常的体系结构

```java
 * java.lang.Throwable
 * 		|-----java.lang.Error:一般不编写针对性的代码进行处理。
 * 		|-----java.lang.Exception:可以进行异常的处理
 * 			|------编译时异常(checked)
 * 					|-----IOException
 * 						|-----FileNotFoundException
 * 					|-----ClassNotFoundException
 * 			|------运行时异常(unchecked,RuntimeException)
 * 					|-----NullPointerException
 * 					|-----ArrayIndexOutOfBoundsException
 * 					|-----ClassCastException
 * 					|-----NumberFormatException
 * 					|-----InputMismatchException
 * 					|-----ArithmeticException
```



![异常结构体系](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-51d5e21c.jpeg)

#### 2. 从程序执行过程，看编译时异常和运行时异常



![image-20210912104049465](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/8919/yank-note-picgo-1dec9723.png)

编译时异常：执行javac.exe命名时，可能出现的异常
运行时异常：执行java.exe命名时，出现的异常



#### 3 常见的异常类型，请举例说明：

```java
//******************以下是运行时异常***************************
	//ArithmeticException
	@Test
	public void test6(){
		int a = 10;
		int b = 0;
		System.out.println(a / b);
	}
	
	//InputMismatchException
	@Test
	public void test5(){
		Scanner scanner = new Scanner(System.in);
		int score = scanner.nextInt();
		System.out.println(score);
		
		scanner.close();
	}
	
	//NumberFormatException
	@Test
	public void test4(){
		
		String str = "123";
		str = "abc";
		int num = Integer.parseInt(str);
		
		
		
	}
	
	//ClassCastException
	@Test
	public void test3(){
		Object obj = new Date();
		String str = (String)obj;
	}
	
	//IndexOutOfBoundsException
	@Test
	public void test2(){
		//ArrayIndexOutOfBoundsException
//		int[] arr = new int[10];
//		System.out.println(arr[10]);
		//StringIndexOutOfBoundsException
		String str = "abc";
		System.out.println(str.charAt(3));
	}
	
	//NullPointerException
	@Test
	public void test1(){
		
//		int[] arr = null;
//		System.out.println(arr[3]);
		
		String str = "abc";
		str = null;
		System.out.println(str.charAt(0));
		
	}

	//******************以下是编译时异常***************************
	@Test
	public void test7(){
//		File file = new File("hello.txt");
//		FileInputStream fis = new FileInputStream(file);
//		
//		int data = fis.read();
//		while(data != -1){
//			System.out.print((char)data);
//			data = fis.read();
//		}
//		
//		fis.close();
		
	}
```



### 1.6.2 异常的处理



#### 1. java异常处理的抓抛模型

```java
过程一："抛"：程序在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个对应异常类的对象。
 *           并将此对象抛出。
 *           一旦抛出对象以后，其后的代码就不再执行。
 * 		
 * 		关于异常对象的产生：① 系统自动生成的异常对象
 * 					     ② 手动的生成一个异常对象，并抛出（throw）
 * 
过程二："抓"：可以理解为异常的处理方式：① try-catch-finally  ② throws
```



#### 2. 异常处理方式一：try-catch-finally

##### 2.1 使用说明：

```java
try{
 * 		//可能出现异常的代码
 * 
 * }catch(异常类型1 变量名1){
 * 		//处理异常的方式1
 * }catch(异常类型2 变量名2){
 * 		//处理异常的方式2
 * }catch(异常类型3 变量名3){
 * 		//处理异常的方式3
 * }
 * ....
 * finally{
 * 		//一定会执行的代码
 * }
 * 
 * 说明：
 * 1. finally是可的。
 * 2. 使用try将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中进行匹配
 * 3. 一旦try中的异常对象匹配到某一个catch时，就进入catch中进行异常的处理。一旦处理完成，就跳出当前的try-catch结构（在没写finally的情况。继续执行其后的代码
 * 4. catch中的异常类型如果没子父类关系，则谁声明在上，谁声明在下无所谓。
 *    catch中的异常类型如果满足子父类关系，则要求子类一定声明在父类的上面。否则，报错
 * 5. 常用的异常对象处理的方式： ① String  getMessage()    ② printStackTrace()
 * 6. 在try结构中声明的变量，再出了try结构以后，就不能再被调用
 * 7. try-catch-finally结构可以嵌套

总结：如何看待代码中的编译时异常和运行时异常？

 * 体会1：使用try-catch-finally处理编译时异常，是得程序在编译时就不再报错，但是运行时仍可能报错。相当于我们使用try-catch-finally将一个编译时可能出现的异常，延迟到运行时出现。
 *     
 * 体会2：开发中，由于运行时异常比较常见，所以我们通常就不针对运行时异常编写try-catch-finally了。针对于编译时异常，我们说一定要考虑异常的处理。
```



##### 2.2 finally的再说明：

```java
* 1.finally是可选的
 * 
 * 2.finally中声明的是一定会被执行的代码。即使catch中又出现异常了，try中return语句，catch中return语句等情况。
 * 
 * 3.像数据库连接、输入输出流、网络编程Socket等资源，JVM是不能自动的回收的，我们需要自己手动的进行资源的释放。此时的资源释放，就需要声明在finally中。
```



##### 2.3 面试题

```java
final、finally、finalize三者的区别？

类似：
throw 和 throws
Collection 和 Collections
String 、StringBuffer、StringBuilder
ArrayList 、 LinkedList
HashMap 、LinkedHashMap
重写、重载

结构不相似的：
抽象类、接口
 、 equals()
sleep()、wait()
```



#### 3. 异常处理方式二：

```java
"throws + 异常类型"写在方法的声明处。指明此方法执行时，可能会抛出的异常类型。
一旦当方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象，此对象满足throws后异常类型时，就会被抛出。异常代码后续的代码，就不再执行！
```



#### 4. 对比两种处理方式

```java
try-catch-finally:真正的将异常给处理掉了。
throws的方式只是将异常抛给了方法的调用者。并没真正将异常处理掉。  
```



#### 5. 体会开发中应该如何选择两种处理方式？

```java
*  5.1 如果父类中被重写的方法没throws方式处理异常，则子类重写的方法也不能使用throws，意味着如果子类重写的方法中异常，必须使用try-catch-finally方式处理。
*  5.2 执行的方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行的。我们建议这几个方法使用throws的方式进行处理。而执行的方法a可以考虑使用try-catch-finally方式进行处理。
    
补充：
方法重写的规则之一：
子类重写的方法抛出的异常类型不大于父类被重写的方法抛出的异常类型
```



### 1.6.3 手动抛出异常对象



#### 1. 使用说明

```java
在程序执行中，除了自动抛出异常对象的情况之外，我们还可以手动的throw一个异常类的对象。
```



#### 2. 面试题]

```java
throw 和  throws区别：
throw 表示抛出一个异常类的对象，生成异常对象的过程。声明在方法体内。
throws 属于异常处理的一种方式，声明在方法的声明处。
```



#### 3. 典型例题

```java
class Student{
	
	private int id;
	
	public void regist(int id) throws Exception {
		if(id > 0){
			this.id = id;
		}else{
			//手动抛出异常对象
//			throw new RuntimeException("您输入的数据非法！");
//			throw new Exception("您输入的数据非法！");
			throw new MyException("不能输入负数");

		}
		
	}

	@Override
	public String toString() {
		return "Student [id=" + id + "]";
	}
	
	
}
```



### 1.6.4 自定义异常类

```java
如何自定义一个异常类？
/*
 * 如何自定义异常类？
 * 1. 继承于现的异常结构：RuntimeException 、Exception
 * 2. 提供全局常量：serialVersionUID
 * 3. 提供重载的构造器
 * 
 */
public class MyException extends Exception{
	
	static final long serialVersionUID = -7034897193246939L;
	
	public MyException(){
		
	}
	
	public MyException(String msg){
		super(msg);
	}
}
```
